const fs=require('fs'),zlib=require('zlib');
let src=fs.readFileSync('tools/site_audit.js','utf8');
const marker='(async()=>{let list=await json(';
const cut=src.indexOf(marker);
if(cut<0)throw new Error('Audit script marker not found');
const inject=String.raw`
const zlib=require('zlib');
function parseCsv(text){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){field+='"';i++}else if(c==='"')quoted=false;else field+=c}else if(c==='"')quoted=true;else if(c===','){row.push(field);field=''}else if(c==='\n'){row.push(field.replace(/\r$/,''));rows.push(row);row=[];field=''}else field+=c}if(field.length||row.length){row.push(field.replace(/\r$/,''));rows.push(row)}const h=rows.shift();return rows.filter(r=>r.some(v=>v!=='')).map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]??''])))}
`;
const tail=String.raw`(async()=>{const packed=fs.readdirSync('data').filter(x=>x.startsWith('site_input.part')).sort().map(x=>fs.readFileSync('data/'+x,'utf8').trim()).join('');const text=zlib.gunzipSync(Buffer.from(packed,'base64')).toString('utf8');let rows=parseCsv(text).map(r=>({...r,stars:Number(r.stars||0),owner_objects:Number(r.owner_objects||0),site:norm(r.site||'')}));let browser=await chromium.launch({headless:true}),ctx=await browser.newContext({viewport:{width:390,height:844},ignoreHTTPSErrors:true,locale:'ru-RU',userAgent:'Mozilla/5.0 (Linux; Android 13) Chrome/149 Mobile'}),uniq=[...new Set(rows.map(r=>r.site).filter(Boolean))],cache=new Map(),u=0,done=0;async function aw(){while(true){let k=u++;if(k>=uniq.length)return;let url=uniq[k],p=await ctx.newPage(),record;try{let m=await audit(p,url),st=[401,403,429].includes(m.httpStatus)?'blocked':m.httpStatus>=400||m.textLength<100?'unreachable':'ok';record={st,m,e:''}}catch(e){record={st:'unreachable',m:null,e:String(e.message||e).slice(0,500)}}await p.close();cache.set(url,record);console.log('audit '+(++done)+'/'+uniq.length+' '+record.st+' '+url)}}await Promise.all(Array.from({length:7},aw));await browser.close();let out=rows.map(r=>{let z=r.site?cache.get(r.site):{st:'no_site',m:null,e:''},s=score(z.m||{},z.st);return{...r,final_url:z.m?.finalUrl||'',site_status:z.st,http_status:z.m?.httpStatus||'',site_score:s.site,technical_score:s.tech,conversion_score:s.conv,content_score:s.cont,trust_score:s.trust,seo_score:s.seo,performance_score:s.perf,modernity_score:s.modern,mobile_ok:z.m?(z.m.viewport&&!z.m.overflow?'Да':'Нет'):'',online_booking:z.m?(z.m.booking?'Да':'Нет'):'',load_ms:z.m?.ms||'',transfer_mb:z.m?.mb||'',problems:s.bad.join('; '),recommendation:rec(s.site,z.st),sales_priority_score:priority(r,s.site,z.st),audit_error:z.e,audit_date:DATE}}).sort((a,b)=>b.sales_priority_score-a.sales_priority_score||a.site_score-b.site_score||a.hotel.localeCompare(b.hotel,'ru'));let H=['rank','id','hotel','site','final_url','site_status','http_status','site_score','technical_score','conversion_score','content_score','trust_score','seo_score','performance_score','modernity_score','mobile_ok','online_booking','load_ms','transfer_mb','problems','recommendation','sales_priority_score','stars','segment','owner_type','owner_objects','previous_priority','audit_error','audit_date'];let lines=[H.map(cell).join(';')];out.forEach((r,i)=>lines.push(H.map(h=>cell(h==='rank'?i+1:r[h])).join(';')));fs.mkdirSync('data',{recursive:true});fs.writeFileSync('data/site_audit_results.csv','\uFEFF'+lines.join('\r\n'));fs.writeFileSync('data/site_audit_results.json',JSON.stringify({total:out.length,audited_sites:uniq.length,audit_date:DATE,results:out},null,2));console.log('DONE '+out.length+' '+uniq.length)})().catch(e=>{console.error(e);process.exit(1)});
`;
fs.writeFileSync('tools/site_audit_runtime.js',src.slice(0,cut)+inject+tail);
require('./site_audit_runtime.js');
